//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialite
    {
        public Specialite()
        {
            this.Stagiaires = new HashSet<Stagiaire>();
        }
    
        public int Code { get; set; }
        public string Spec { get; set; }
    
        public virtual ICollection<Stagiaire> Stagiaires { get; set; }
    }
}
