//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaire
    {
        public int num { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public int Code { get; set; }
    
        public virtual Specialite Specialite { get; set; }
    }
}
